### ISSUE TITLE
Neordigita nombroj

### ISSUE THREAD

**Issue by benahm** [Esperanto/kurso-zagreba-metodo#100]
http://learn.esperanto.com/{lingvokodo}/diversajxoj/
## ![1](https://cloud.githubusercontent.com/assets/3356566/15850198/102ffbdc-2c97-11e6-9b4d-7d4e747b9590.png)

Vidu supre :

unu: one
du: two
tri: three
kvar: four
kvin: five
ses: six
sep: seven
ok: eight
naŭ: nine
dek: ten
dek unu: eleven
dek du: twelve
dek tri: thirteen
dek kvar: fourteen
dek kvin: fiveteen 
dek ses: sixteen 
dek sep: seventeen
dek ok: eightteen
dek naŭ: nineteen
dudek: twenty
tridek: thirty
kvardek: fourty
cent: hundred
ducent: two hundred
tricent: three hundred
mil: thousand
dumil: two thousand

**Comment by jorges-intrax** [comment]
Jes, bona propono. Fakte mi pensis pri simple uzi la ciferojn, kaj le traduki tion per vortoj, ekzemple:

- mil: 1000
- dumil: 2000

Bonus?

**Comment by georgjaehnig** [comment]
Riparita en 75dbef293e4013d639a47195506b3ce96c66952d.
