### ISSUE TITLE
Ideo: Aldonu Disqus komentejo ĉe ĉiuj lingvoversioj

### ISSUE THREAD

**Issue by georgjaehnig** [Esperanto/kurso-zagreba-metodo#102]
Tiel lernanto povus facile komenti pri eraroj ktp.

**Comment by GrizaLeono** [comment]
Jes, tio unuavide ŝajnas tre bona. Ĉu estas jam klare, kiu respondu la komenton?

**Comment by georgjaehnig** [comment]
Testa version funkciante, nun por la sveda kaj nederlanda:
http://learn.esperanto.com/nl/01/
http://learn.esperanto.com/sv/01/

Se vi volas testi ankaŭ en via lingvo, skribu.

**Comment by Ludovacae** [comment]
Hoi,

Verloopt alles naar wens?

Ik zal het doornemen ;)

Ciao

**Comment by georgjaehnig** [comment]
Jam farita por
- nl
- sv
- en
- sl
- e
Skribu al mi / komentu ĉi tie se vi ankaŭ volas komentejon en via lingvoversio.

**Comment by warut92** [comment]
Jes, ankaŭ mi volas en la taja lingvoversio. :)

Warut.

2016-11-30 18:52 GMT+07:00 Georg Jähnig <notifications@github.com>:

**Comment by georgjaehnig** [comment]
Bone, aliĝu senpage al https://disqus.com/ kaj sendu al mi vian uzantnomon.

**Comment by warut92** [comment]
Jam farite
Mia uzantnomo estas Warut

Warut

เมื่อ 30 พ.ย. 2016 23:20 "Georg Jähnig" <notifications@github.com> เขียนว่า

**Comment by Ludovacae** [comment]
Dankon;)
