### ISSUE TITLE
Nomado de partoprenantoj en AUTHORS.md

### ISSUE THREAD

**Issue by miestasmia** [Esperanto/kurso-zagreba-metodo#111]
Saluton
Ŝajnas al mi iom strange ke neniuj tradukistoj estas nomitaj en AUTHORS.md aŭ eĉ aliloke por montri kiuj tradukis kiujn lingvojn ktp.
Al mi ŝajnas la plej taŭga solvo aldoni sekcion al AUTHOR.md kun nomoj de ĉiuj tradukistoj kaj iliaj respektivaj lingvoj.

**Comment by Reedych** [comment]
https://github.com/Esperanto/kurso-zagreba-metodo/blob/master/agordoj/lingvoj.yml

**Comment by georgjaehnig** [comment]
En `AUTHORS.md` skribitas

> La laŭlingvajn aŭtorojn de la ciferecigo troviĝas en `[agordoj/lingvoj.yml](agordoj/lingvoj.yml)`.

Mi nun elkribis la dosiernomon.

**Comment by georgjaehnig** [comment]
Ankaŭ la nomoj troviĝas en la retejo sube sub la ligilo "Aŭtoroj", ekzemple:
https://learn.esperanto.com/da/auxtoroj/

**Comment by miestasmia** [comment]
Ha bonege, mi tute maltrafis tion. Dankon!
