### ISSUE TITLE
La permisilo ne eblas uzi la verkon en Vikimediaj projektoj

### ISSUE THREAD

**Issue by psychoslave** [Esperanto/kurso-zagreba-metodo#115]
Saluton,

Estus interesa se la verko de tiu deponejo povus ankaŭ esti uzita en Vikimediaj projektoj. Tio ekzemple ebligus aliron al la verko por personoj kiuj retumas je [Wikipedia Zero](https://en.wikipedia.org/wiki/Wikipedia_Zero).

Kore,
psychoslave

**Comment by miestasmia** [comment]
Mi konsentas kun la ideo, sed tio postulus aprobon de ĉiuj kontribuintoj. Tio verŝajne ne eblus.

**Comment by georgjaehnig** [comment]
@psychoslave La permisiloj estas la jenaj:
https://github.com/Esperanto/kurso-zagreba-metodo#permesiloj

Mi ne scias ĉu tio sufiĉas – ĉu?

**Comment by psychoslave** [comment]
@georgjaehnig, mi jam vidis la permisilon, kaj redaktis la atentindaĵon ĉar ĝi ne estas kongrua kun kondiĉoj de Vikimedia uzado, nur liberaj permisloj taŭgas. Precize, la "neŝanĝeble" kondiĉo ne taŭgas.

@miestasmia laŭ github, nur 58 personoj partoprenis la projekton. Tio ne estas tiom multe. Plie, se ĉiuj la kontribuoj uzis git, ili retadreso estas konita, do sendi peton estas tute ebla. Se la plej granda parto respondus pozitive, estus facila anstataŭi la kontribuoj de tiuj kiuj malkonsentas. Almenaŭ multe pli facila ol skribi tute novan kurson.

**Comment by georgjaehnig** [comment]
Bone, do temas pri la "neŝanĝeble" kondiĉo. Pri tio ni jam diskutis en #38.

Sciu ke tiu ĉi kurso ne estas kreita nur per la Github uzantoj, sed la esperantaj tekstoj venas de kroataj aŭtoroj, kreinte ilin en la 1980aj jaroj. Legu pli jen: https://eo.wikipedia.org/wiki/Zagreba_metodo

Mi demandis ilin pri permesiloj kaj ili nur konsentis, se la tekstoj havas la "neŝanĝeble" kondiĉo.

**Comment by psychoslave** [comment]
Jes mi jam estis leganta la Vikipedia artikolo. 😄 

Se vi havas kontakton, eble vi povus ankaŭ afable demandi kun eksplikoj pri la kialo tio gravas kaj kiel tio efikus multoble la dissendon de la verko kaj do de Esperanto. Aŭ eble vi povus sendi al mi kontaktojn. 

Kore

**Comment by psychoslave** [comment]
Mi finis legi la artikolon kaj vidis la retadresojn ĉi tie, ĉi gi estas tiujn ke vi uzis @georgjaehnig ?

**Comment by georgjaehnig** [comment]
Nu, en la artikolo ja estas kontakto de Zlatko, ĉe la parto "Plia adaptigo kaj traduko".

Mi ankaŭ persone parolis kun Zlatko ĉe UK 2016 kaj li havas bonajn argumentojn por la "neŝanĝeble" kondiĉo. Kiel:

> Ĉe la adaptoj gravas, ke ili ne estu ŝanĝitaj, ĉar nur identaj ili estas uzeblaj internacie.

Cetere, mi mem ne kredas ke pli libera permesilo tiom grave efikus la dissendon. Ekzemple la Duolingo kursoj tute ne estas liberaj, sed multoblege pli uzataj ol ĉi tiu kurso kun relative libera permesilo.

Pli gravas kiom da homoj fakte laboras pri la enhavo, la konigu, la programado ktp. Tion oni ja bezonus ankaŭ por havigi ĝin en Wikipedia Zero. Tial mi rekomendas ke antaŭ komenci novan debaton kun Zlatko pri la permisilo, pli indus pensi: Kion mi mem volus fari / labori por dissendi la kurson?

**Comment by psychoslave** [comment]
Mi tute ne komprenas la argumenton. Mi impresas ke tio estas pri timo de malbona ŝanĝoj. Sed eĉ por sen signifa ŝanĝoj, permeso de ŝanĝo multe gravas. Fakte mi ne certas kio tio nuna projekto faras ekzakte kun la enhavo de la kurso, sed bona ŝancoj estas ke ĝi modifas ĝin pro montrigi la datenojn laŭ ajn datenaranĝo.

Por integri la kurso al Vikimedia projekto oni necesus adapti ĝin al la Mediakivia kodo kaj medio. Malpermsi ŝanĝoj de la verko faras tiun malebla. Plie por la prezenta kazo, tiu ja vere gravas, ĉar ĝi malpermesas uzi ĝin ene de Vikimidia movado.

> Kion mi mem volus fari / labori por dissendi la kurson?

Mi volas labori al la integrigo de bonaj Esperanto kursoj, kiel zakgrebra metodo, en la Vikimedia projektoj. Mi kredas ke tio povus helpi dissendi la kurson. Sed la nuna permisilo malpermesas tion.

**Comment by georgjaehnig** [comment]
> Mi tute ne komprenas la argumenton. Mi impresas ke tio estas pri timo de malbona ŝanĝoj.

Ne, temas ĉefe pri tio, ke per samaj (esperantaj) tekstoj, oni certigas ke ĉiuj lingvoversioj estas la samaj.

Sed bone, se vi volas, demandu la aŭtorojn.

> sed bona ŝancoj estas ke ĝi modifas ĝin pro montrigi la datenojn laŭ ajn datenaranĝo.

Jes, klare.

Do, la deziro de la aŭtoroj estas ke la esperantaj tekstoj restas neŝanĝitaj. Se vi havas pli bonan ideon ol la "ND" kondiĉo por

- permesi teknikan modifon
- sed ankaŭ malpermesi enhavan modifon

diru ĝin al mi.

(Mi jam [demandis tion antaŭe](https://github.com/Esperanto/kurso-zagreba-metodo/issues/38#issuecomment-212601612) sed ne ricevis respondon.

> Por integri la kurso al Vikimedia projekto oni necesus adapti ĝin al la Mediakivia kodo kaj medio

Ĉu mi komprenas bone ke tiam la kurso estus en la formo de simplaj Mediavikaj retpaĝoj, kiel Wikibooks?

Cetere, ĉu vi jam konas https://en.wikibooks.org/wiki/Esperanto/Contents ?

**Comment by psychoslave** [comment]
>Ne, temas ĉefe pri tio, ke per samaj (esperantaj) tekstoj, oni certigas ke ĉiuj lingvoversioj estas la samaj.

Por tio la BY klaŭzo sufiĉas, ĉar la uzulo ĉiam ricevos ligo al origina teksto kaj do povas kontroli la diferencojn – se la eldonisto respektas la permesilo, kompreneble, sed alie neniu permisilo ŝanĝas tion.

>  Se vi havas pli bonan ideon ol la "ND" kondiĉo por […]

Mi opinias ke ND neniam estas dezirebla. Laŭ mi tiu ne estas nur maltaŭga rimedo, tio estas superregi la derivaĵojn kiu estas kontraŭefika celo. Pli bone estas lasi ĉiujn fari ajn modifojn ili deziras dum proponi klaran vojon por kontribui en origina deponejo kiu povas havi pli striktaj akceptaj konvencioj. Sed tio estas mia opinio, kompreneble.

**Comment by psychoslave** [comment]
> Ĉu mi komprenas bone ke tiam la kurso estus en la formo de simplaj Mediavikaj retpaĝoj, kiel Wikibooks?

Depende de kio vi signifas per "simpla", jes aŭ ne. Ĉar vi ja povas krei kvizoj, aŭ uzi aliajn Ĝavoskriptajn ilojn, aŭ eĉ krei novan kromâjo de Mediavikio se necesas. 

>Cetere, ĉu vi jam konas https://en.wikibooks.org/wiki/Esperanto/Contents ?

Mi trovis ĝin tute freŝdate, sed dankon por la ligo, kaj se vi konas aliajn rimedojn kiel tiu ĉi, mi estas ege interesita. Mi ne jam ellegis la kurso, do mi ne jam havas opinion pri ĝia kvalito. Fakte, mi ne jam ellegis la zagebran kurson, do mi ne povus kompari la kvaliton. Se vi ja ellegis ambaŭ, mi estas interesita pri via opinio.

Se la Wikibooks estas sufiĉe bona kvalito, eble mi povas prefereble koncentri mian tempon al traduki kaj plibonigi ĝin.

**Comment by psychoslave** [comment]
Kaj mi ankaŭ volus scii se la frekvencoj de plej oftaj uzita vortoj estas havebla ie kaj kun kiel kondiĉoj. Fakte, mi kredas ke oni povus egale krei novan statistikojn per analizado de Vikimediaj esperantaj projektoj. 💡
