### ISSUE TITLE
Kreu PDF (kaj EPUB) eligon

### ISSUE THREAD

**Issue by georgjaehnig** [Esperanto/kurso-zagreba-metodo#120]
Foje indas havi la enhavon kiel PDF.

De la Markdown-kaj YAML-fonto verŝajne ne komplikas krei unu grandan Markdown-dosieron, kaj per de tiu per `pandoc` eligon en PDF (kaj eĉ EPUB).

**Comment by nesrad** [comment]
Tiu ĉi propono ege plaĉas min. Ankaŭ plaĉus kiun ajn formon el pandoc elŝuti, ne nur pdf aŭ epub.

**Comment by Donesra** [comment]
Multaj homoj preferas studi kun presita papero, do mi pensas ke via ideo estas oportunega. Ne ĉiuj havas aŭ volas havi poŝtelefonon, kaj eĉ se ili havas, foje ne povas uzi ĝin pro malbona aŭ neekzistanta poŝtelefona kovrado.

**Comment by georgjaehnig** [comment]
Fakte tio jam estis farita, mi nun ĝisdatigis la `README.md` kaj malfermas tiun ĉi petoslipon. :)

https://github.com/Esperanto/kurso-zagreba-metodo/blob/master/README.md#pdf-kaj-epub

**Comment by Donesra** [comment]
Jen kio okazis kiam mi provis fari pdf-dosieron.
![Screenshot at 2019-08-06 17-22-49](https://user-images.githubusercontent.com/19158792/62578369-f6521a80-b86e-11e9-9d2d-ab1be5d8843a.png)
![Screenshot at 2019-08-06 17-23-39](https://user-images.githubusercontent.com/19158792/62578371-f81bde00-b86e-11e9-8ae3-697a0cb1c7f5.png)

**Comment by georgjaehnig** [comment]
Mi supozas ke vi uzas malnovan version de Pandoc. Kiun vi uzas?

**Comment by Donesra** [comment]
1.16.0.2
Mi provos altgradigi ĝin.

**Comment by Donesra** [comment]
Nun bone sukcesis :) dankon por la helpo.
![Screenshot at 2019-08-06 17-51-33](https://user-images.githubusercontent.com/19158792/62580038-4fbc4880-b873-11e9-8c0f-f506d3c232d0.png)
![Screenshot at 2019-08-06 17-52-05](https://user-images.githubusercontent.com/19158792/62580041-50ed7580-b873-11e9-8a96-2d310c5a4cf5.png)

**Comment by georgjaehnig** [comment]
Bele. Mi ankaŭ ĝisdatigis `README.md`, ankaŭ per la informo kiel [limigi la enhavon](https://github.com/Esperanto/kurso-zagreba-metodo/blob/master/README.md#limigu-enhavon).
