### ISSUE TITLE
Kreu veran Anki eligon

### ISSUE THREAD

**Issue by georgjaehnig** [Esperanto/kurso-zagreba-metodo#128]
Per [genanki](https://github.com/kerrickstaley/genanki) oni povas krei proprajn `*.apkg` dosierojn, kiujn oni rekte kaj facile provas importi en [Anki](https://apps.ankiweb.net/).

Kreu tion eligon por la vortoj en ĉiu lingvo.

**Comment by nesrad** [comment]
Mi ne komprenas kion genanki faras ke Anki mem ne povas fari?

**Comment by axel584** [comment]
Gxi ebligas aùtomate krei sliparon por Anki. Tiel, el datumbazo (aù teksta dosiero), vi povas generi anki dosierojn sen fari ilin "mane"

**Comment by georgjaehnig** [comment]
Ne temas pri

- genanki vs Anki, 
- sed genanki vs. la nuna TSV-eligo

vidu jen: https://learn.esperanto.com/en/01/vortoj/

Nun oni devaj komplike importi la `*.tsv` al Anki, per genanki oni havos `*.apkg` kiu facilege importeblas.

**Comment by das-g** [comment]
> Mi ne komprenas kion genanki faras ke Anki mem ne povas fari?

Krei Anki-Deck-ajn dosierojn _programe_. Do, ekz. ĉe https://learn.esperanto.com/de/01/vortoj/, ni povus ofri `*.apkg`-an dosieron anstataŭ `*.tsv`-an dosieron. `*.apkg`-an dosieron oni povas uzi en ekzemple AnkiDroid direkte, sen bezoni https://api.ankiapp.com/nexus/
