### ISSUE TITLE
Ĝustigado de Vortoj

### ISSUE THREAD

**Issue by Konotorious** [Esperanto/kurso-zagreba-metodo#131]
Pardonu anglla lingvo mia. Mia esperanto estas verŝajne ne sufica bona.

While studying with the course (which I very much appreciate!), I noticed some minor mistakes in the "new words" sections of lessons. I wanted to correct them and the create a pull request. However, I found it hard to find where exactly I was suppose to insert the corrections. It seems a very large part of the site is generated (which is impressive by itself). I saw some roots in one file (though no adjektivo.yml file?), and then lists of roots for each lesson. Any assistance in finding my way in the files would be appreciated. Dankon!

**Comment by georgjaehnig** [comment]
Hi, yes, the complete site is generate out of YAML- and Markdown files. ;)

The list of *New words* is partly generated by those who appear in the text for the first time (From the text) and some other (More).

Translations of *More* come from `tradukenda/en/vortaro/novaj.yml`.

Translations of *From the text* are scattered in the files in `tradukenda/en/vortaro/`, depending on their word category.

If you need more help finding the right file, feel free to ask!

**Comment by Konotorious** [comment]
Dankon! Mi enrigardos al ĝi.
