### ISSUE TITLE
la vortoj 'suko' kaj 'las' 

### ISSUE THREAD

**Issue by Donesra** [Esperanto/kurso-zagreba-metodo#132]
En la Novaj Vortoj de la tria leciono oni vidas la vorton 'suko', kaj en la sepa leciono oni havas 'las' (sen finaĵo). Ĉi tiuj vortoj mankas tradukojn en kelkaj lingvoj, sed mi ne vidas kie oni povas aldoni tradukon en la franca kaj la angla.

**Comment by georgjaehnig** [comment]
Ho vere. Jes, ili mankis en `enhavo/tradukenda/en/vortaro/novaj.yml`. Mi nun aldonis ilin por la angla, por la franca en la sama dosiero.

**Comment by das-g** [comment]
Por kiel fari tion, vidu fa75ada63088e629d95b72723f13da51655ba103 kaj df76dc1fde7211bb299b4a2d9d0853e8fbc27a2f.

**Comment by georgjaehnig** [comment]
@das-g Dankon!
