### ISSUE TITLE
Generi html

### ISSUE THREAD

**Issue by abacoti** [Esperanto/kurso-zagreba-metodo#150]
python generate.py --lingvo en --eligformo html
    
    C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master>python generate.py --lingvo en --eligformo html
    Traceback (most recent call last):
      File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\generate.py", line 222, in <module>
        html_generiloj.generi.generate_html(args.lingvo, enhavo, args)
      File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\html_generiloj\generi.py", line 123, in generate_html
        md = mistune.Markdown()
    TypeError: Markdown.__init__() missing 1 required positional argument: 'renderer'

**Comment by georgjaehnig** [comment]
Mi ne puŝis la lastajn ŝanĝojn. Bv. provu denove.

**Comment by abacoti** [comment]
C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master>python generate.py --lingvo en --eligformo html
Traceback (most recent call last):
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\generate.py", line 228, in <module>
    main()
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\generate.py", line 212, in main
    lingvoj = yaml.load(open('agordoj/lingvoj.yml').read(), yaml.Loader)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 238: character maps to <undefined>

tiu mi solvas aldoninte ", encoding="utf-8" en ĉiuj OPEN metodo.  Post tion mi havas saman resulton!: 
 C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master>python generate.py --lingvo en --eligformo html
Traceback (most recent call last):
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\generate.py", line 228, in <module>
    main()
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\generate.py", line 219, in main
    html_generiloj.generi.generate_html(args.lingvo, enhavo, args)
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\html_generiloj\generi.py", line 123, in generate_html
    md = mistune.Markdown()
TypeError: Markdown.__init__() missing 1 required positional argument: 'renderer'

**Comment by georgjaehnig** [comment]
Kia estas via eligo ĉe

   pip freeze

?

**Comment by abacoti** [comment]
C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master>pip freeze
cached-property==1.5.2
chevron==0.14.0
frozendict==2.3.2
genanki==0.13.0
Jinja2==3.1.2
MarkupSafe==2.1.1
mistune==2.0.3
PyYAML==6.0

**Comment by georgjaehnig** [comment]
Dankon. Vi uzas tro novajn versiojn. Vi devas uzi tiajn de `requirements.txt`.

Do helpus fari `pip install -r requirements.txt`.

**Comment by abacoti** [comment]
C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master>python generate.py --lingvo en --eligformo html
Traceback (most recent call last):
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\generate.py", line 10, in <module>
    import html_generiloj
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\html_generiloj\__init__.py", line 1, in <module>
    from .generi import *
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\html_generiloj\generi.py", line 10, in <module>
    import jinja2
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\env\lib\site-packages\jinja2\__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\env\lib\site-packages\jinja2\environment.py", line 16, in <module>
    from jinja2.defaults import BLOCK_START_STRING, \
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\env\lib\site-packages\jinja2\defaults.py", line 32, in <module>
    from jinja2.tests import TESTS as DEFAULT_TESTS
  File "C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master\env\lib\site-packages\jinja2\tests.py", line 13, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\User\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

**Comment by abacoti** [comment]
ĉu la versio de Python?

**Comment by georgjaehnig** [comment]
Bv. skribu iom plu, ne nur algluu la erar-eligojn.

Ĉu vi faris `pip install -r requirements.txt`? Ĉu estis iu eraro tie? Kio nun okazas per `pip freeze`?

**Comment by abacoti** [comment]
C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master>pip install -r requirements.txt
Collecting PyYAML==3.12
  Downloading PyYAML-3.12.zip (375 kB)
     ---------------------------------------- 375.8/375.8 kB 2.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting Jinja2==2.10
  Downloading Jinja2-2.10-py2.py3-none-any.whl (126 kB)
     ---------------------------------------- 126.4/126.4 kB 1.9 MB/s eta 0:00:00
Collecting MarkupSafe==2.0.1
  Downloading MarkupSafe-2.0.1-cp310-cp310-win_amd64.whl (15 kB)
Collecting mistune==0.8.4
  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: genanki==0.13.0 in c:\compart\esperanto\zm\kurso-zagreba-metodo-master\env\lib\site-packages (from -r requirements.txt (line 5)) (0.13.0)
Requirement already satisfied: chevron in c:\compart\esperanto\zm\kurso-zagreba-metodo-master\env\lib\site-packages (from genanki==0.13.0->-r requirements.txt (line 5)) (0.14.0)
Requirement already satisfied: frozendict in c:\compart\esperanto\zm\kurso-zagreba-metodo-master\env\lib\site-packages (from genanki==0.13.0->-r requirements.txt (line 5)) (2.3.2)
Requirement already satisfied: cached-property in c:\compart\esperanto\zm\kurso-zagreba-metodo-master\env\lib\site-packages (from genanki==0.13.0->-r requirements.txt (line 5)) (1.5.2)
Building wheels for collected packages: PyYAML
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-3.12-cp310-cp310-win_amd64.whl size=43069 sha256=8e1533bfa904707d44731ddce6744569ccfc78bdf7e7e57b3f0c096d54828f1a
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\07\6e\47\016d2f3eb7e630a7ad552d6bdfbd570696d74267a47e88d48a
Successfully built PyYAML
Installing collected packages: PyYAML, mistune, MarkupSafe, Jinja2
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 6.0
    Uninstalling PyYAML-6.0:
      Successfully uninstalled PyYAML-6.0
  Attempting uninstall: mistune
    Found existing installation: mistune 2.0.3
    Uninstalling mistune-2.0.3:
      Successfully uninstalled mistune-2.0.3
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 2.1.1
    Uninstalling MarkupSafe-2.1.1:
      Successfully uninstalled MarkupSafe-2.1.1
  Attempting uninstall: Jinja2
    Found existing installation: Jinja2 3.1.2
    Uninstalling Jinja2-3.1.2:
      Successfully uninstalled Jinja2-3.1.2
Successfully installed Jinja2-2.10 MarkupSafe-2.0.1 PyYAML-3.12 mistune-0.8.4

**Comment by abacoti** [comment]
kaj nun ĝi estas tie:
C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master>pip freeze
cached-property==1.5.2
chevron==0.14.0
frozendict==2.3.2
genanki==0.13.0
Jinja2==2.10
MarkupSafe==2.0.1
mistune==0.8.4
PyYAML==3.12

**Comment by georgjaehnig** [comment]
Bone. Kaj nun, vi havas daŭre erarojn?

Jes, kio estas la eligo de `python --version`?

**Comment by abacoti** [comment]
C:\Compart\Esperanto\ZM\kurso-zagreba-metodo-master>python --version
Python 3.10.5

**Comment by georgjaehnig** [comment]
Hm, strange. Mi ne povas rekonstrui la eraron. Ĉe mi funkcias:

    $ pip3 freeze
    cached-property==1.5.2
    chevron==0.14.0
    frozendict==2.3.2
    genanki==0.13.0
    Jinja2==2.10
    MarkupSafe==2.0.1
    mistune==0.8.4
    PyYAML==3.12

    $ python3 --version
    Python 3.9.13

    $ python3 generate.py --lingvo en --eligformo html
    [sen eraro]

Via eraro [ĉi tie](https://github.com/Esperanto/kurso-zagreba-metodo/issues/150#issuecomment-1179729127) venas de Jinja – mi ĵus guglis kaj trovis [tion](https://stackoverflow.com/a/70557518). Do jes, provu per Python 3.9.

**Comment by abacoti** [comment]
Ĝi bone funkciis nun! Dankon!!!

**Comment by XaviP** [comment]
> Via eraro ĉi tie venas de Jinja – mi ĵus guglis kaj trovis tion.

Jes, see https://github.com/Esperanto/kurso-zagreba-metodo/issues/154
