### ISSUE TITLE
Mankas permesilo

### ISSUE THREAD

**Issue by LaPingvino** [Esperanto/kurso-zagreba-metodo#24]
Sen permesilo oni devas supozi ke la enhavo estas sub plena kopirajto.

**Comment by pizzamaker** [comment]
Mi sugestas "AGPLv3 aŭ poste"

**Comment by LaPingvino** [comment]
mi persone sugestas MIT-permesilon ;) sed ni devas peti al Zlatko kion li permesas kaj kio ne?

**Comment by georgjaehnig** [comment]
Mi parolis kun Zlatko kaj li respondis:

> La autoroj (estas kvar: Zlatko Tišljar, Spomenka Štimec, Ivica Špoljarec kaj Roger Imbert) havas nur unu kondichon: ke niaj nomoj restu en chiuj lokoj kie oni uzas la metodon. Do, ni konsentas ke ghi estus libera por kiu ajn uzo kaj apliko, sed devas resti na nomo Zagreba Motodo kaj niaj kvar nomoj de la autoroj.

Do mi elektis la [Krea Komunaĵo – Atribuite 4.0 Tutmonda (CC BY 4.0)](PERMESILO.md).
