### ISSUE TITLE
CC BY-ND ne estas adekvata permisilo liberkoda.

### ISSUE THREAD

**Issue by IBPX** [Esperanto/kurso-zagreba-metodo#38]
Kaj kial uzi ND iel ajn? Ĝi nur haltis la celon de la Creative Commons-permisilo.

Kial ne nur uzi CC BY, aŭ CC BY-SA? Ĝi pli bonas por ĉio.

**Comment by jorges-intrax** [comment]
Saluton,

ni uzas ND por la esperantaj tekstoj (kaj nur por ili – **la tuta resto havas la CC-BY-permesilon**), ĉar ni volas savi la fakto ke la kurso kovras la 500 plej oftajn vortojn. Se oni povus ŝanĝi la esperantajn tekstojn kaj ekzemple forigi kelkajn vortojn, la kurso ja ne plu havos la 500 plej oftajn vortojn.

Sed intertempe mi eksciis ke la ND permesilo eble ne taŭgas ĉar laŭpermesile oni ankaŭ ne povus ŝanĝi la dosierformojn – kaj ekzemple krei PDF-eldonaĵojn.

Tial, mi ege interesas pri trovi pli taŭgan permesilon: Permesilon, kiu permesas ŝanĝi la eligformon de la tekstojn kaj la uzado en aliaj projektoj – sed ne permesas ŝanĝi la tekstojn mem. Ĉu vi konas tia permesilo?

**Comment by georgjaehnig** [comment]
Saluton,

ni uzas ND por la esperantaj tekstoj (kaj nur por ili – **la tuta resto havas la CC-BY-permesilon**), ĉar ni volas savi la fakto ke la kurso kovras la 500 plej oftajn vortojn. Se oni povus ŝanĝi la esperantajn tekstojn kaj ekzemple forigi kelkajn vortojn, la kurso ja ne plu havos la 500 plej oftajn vortojn.

Sed intertempe mi eksciis ke la ND permesilo eble ne taŭgas ĉar laŭpermesile oni ankaŭ ne povus ŝanĝi la dosierformojn – kaj ekzemple krei PDF-eldonaĵojn.

Tial, mi ege interesas pri trovi pli taŭgan permesilon: Permesilon, kiu permesas ŝanĝi la eligformon de la tekstojn kaj la uzado en aliaj projektoj – sed ne permesas ŝanĝi la tekstojn mem. Ĉu vi konas tia permesilo?

**Comment by IBPX** [comment]
Se vi uzas CC BY _4.0,_ se iu ŝanĝas ion ajn, ĝi **devas** diri ke ili ŝangis ĝin, kaj kion ili ŝanĝis.

Ekzemple, se mi volas uzi nur duone da un' de la tekstoj, mi ne povas. Kun ND, mi devas uzi la tutan aĵon.

Se oni forigas vortojn, tiuj ŝanĝoj ne estos en la vera kurso -- tio ĉi -- nur en tiu homoa ŝanĝita versio, kiam ni devas diri ke ilis ŝanĝis ĝin, kaj diri kiu faris la originalan version.

Mi pensas ke CC BY _4.0_ estus la plej bona; se vi uzas ĝin, jes, homoj povas forigi vortojn, sed nur en ilia versio, kaj ili _devas_ diri ke tio ne estas la vera originala kurso. Tiel, se homoj faras ion, ke vi ne ŝatas, homoj scios ke ĝi ne estas la originala versio.

**Comment by IBPX** [comment]
Se mi volas uzi iom da la tekso en mia persona aĵo, aŭ aldoni vortojn, aŭ eĉ _helpi_ la projekton, mi ne povas kun ND. ND estas terura por liberaj projektoj.

**Comment by georgjaehnig** [comment]
Do, mi devas aldoni ke mi mem proponis uzi la CC-BY permesilon por la tuta projekto sed la originalaj kursaŭtoroj volis ke la tekstoj restas neŝanĝitaj. Mi jam argumentis kiel vi sed ilia deziro restis.

Mi tamen ne pensas ke la nuna solvo estas "terura". Jes, vi ĉiam devas uzi la tutajn tekstojn. Sed mi ne vidas grandan problemon tie:

- Se vi faros vian retpaĝon, nu, uzu ĉiujn tekstojn.
- Se vi faros vian saĝtelefonan aplikaĵon, nu, uzu ĉiujn tekstojn.
- Se vi faros vian PDF-libron, nu, uzu ĉiujn tekstojn.

Se vi vidas faktan problemon, bonvole klarigu tian problemon per ekzemplo(j) al mi, eble mi ŝanĝos mian opinion.

**Comment by Kamparano** [comment]
Mi konsentas, ND malbonas por ĉiuj. Bonvole nur uzu BY.

**Comment by IBPX** [comment]
Pripensu tion: la Aventuroj de Alicio en Mirlando estas publikhavaĵo nun; iu ajn povas ŝanĝi ĝin. Sed nenio malbona okazas al ĝi. Sed, bonegajn aĵojn faris! [Jen listo de la aĵoj homoj faris ĉar ĝi estis publikhavebla!](https://en.wikipedia.org/wiki/Alice%27s_Adventures_in_Wonderland#Adaptations)

> No Derivative Works. You may not alter, transform, or **build upon this work.**

Kun ND, nenio povas uzi ĝin por boneco! Ili ne povas ŝanĝi ĝin por igi ĝin pli bona, aŭ uzi eron da ĝin en filmeto, aŭ io ajn. Kiu ajn decidis uzi ND frenezas.

**Comment by IBPX** [comment]
Se vi uzas ND, ĝi **ne eĉ leĝas kontribui al ĝi sur tiu ĉi GitHub-projekto!**

**Comment by georgjaehnig** [comment]
Do, kiel mi skribis, mi devas respekti la deziron de la aŭtoroj ke la tekstoj devas resti neŝanĝitaj.

Pri la fakto ke la ND eble ne taŭgas ĉar ĝi ankaŭ malpermesas pliajn uzadojn, vi eble pravas. Tial mi supre skribis:

>Tial, mi ege interesas pri trovi pli taŭgan permesilon: Permesilon, kiu permesas ŝanĝi la eligformon de la tekstojn kaj la uzado en aliaj projektoj – sed ne permesas ŝanĝi la tekstojn mem. Ĉu vi konas tia permesilo?

Ĉu vi povas helpi tie?

**Comment by IBPX** [comment]
Kial vi ne volas homoj ebli ŝanĝi la tekston? Tio stultas, kaj estas kontraŭ-libera.

**Comment by georgjaehnig** [comment]
Bone, ŝajnas ke vi ne legas kion mi skribas aŭ ne volas kompreni min. Tio estas malĝoja.

Mi ne ripetos min. Se vi poste volos helpi min pri la lasta demando, mi ĝojus legi de vi. Dankon!

**Comment by IBPX** [comment]
Okej, la respondo al via demando: Ne. Ne ekzistas permisilo kiel tio, ĉar ĝi ne helpus iun ajn.

**Comment by psychoslave** [comment]
Alia eblo estus ne uzi la originan verkon de la zagebra kurso, sed nur la metodo. Oni povas ekzemple analizi vortoftecon el Vikimediaj projektoj, kaj krei novan kurson el tio.
