### ISSUE TITLE
Memfaranta ĝisdatigo de la retejo

### ISSUE THREAD

**Issue by georgjaehnig** [Esperanto/kurso-zagreba-metodo#82]
Oni trovu memfaranta manieron de la ĝistatigo de la [retejo](http://learn.esperanto.com). Tiel la ŝanĝoj pli rapide videblas.

**Comment by Jxajroad** [comment]
Saluton kara Georg!

Emiljo petis al mi sendi al aliaj kunlaborantoj mankantajn arĥivojn.
Bonvole... se eblas al vi diru vi al ni kiuj mankas por fini portugala
parto de zagreba interenta kurso. Vi povas disdoni la mankantajn arĥivojn
al mi kaj al tiu ĉi 3 homoj (Sise'ro; Fred kaj Danieel)

cicero.soares@capgemini.com
fredlopes@yandex.com
danielpmsf@hotmail.com

Bonderire,

Ĵajro


2016-05-09 12:56 GMT-03:00 Georg Jähnig <notifications@github.com>:

**Comment by georgjaehnig** [comment]
Farita.
