### ISSUE TITLE
Confusing word used in lessons "Amikino" 

### ISSUE THREAD

**Issue by ph1234k** [Esperanto/kurso-zagreba-metodo#83]
In lesson 1 girl-friend is regularly translated as amikino. This is confusing as amikino means a friend. It just happens to indicate that friend is female. What we call girl-friend in English would translate to koramikino in Esperanto. 

I understand this is likely just an ambiguous situation but we should use clear examples to avoid such confusion

**Comment by ph1234k** [comment]
Working through lesson 2 this seems to remain consistently confusing as it introduces Ana as Marko's friend who is female and says that he loves her at the end of the reading which would causes ambiguity as to whether she is his amikino or his koramikino. 

Beginning learners are going to assume the latter and learn the wrong word for this relationship.

**Comment by AntoniaMontaro** [comment]
I agree

**Comment by jorges-intrax** [comment]
> What we call girl-friend in English would translate to koramikino in Esperanto.

So what I learned is:

- girlfriend = koramikino
- girl-friend = amikino

But that might be wong, I'm not a native speaker.

I am totally open to better suggestions from native speakers.

**Comment by ph1234k** [comment]
@jorges-intrax 
I think my hyphen confused the meaning. 

To clarify, female romantic partner: koramikino
A friend that happens to be a female: amikino

If I was to translate from Esperanto to English, based on their use of amikino, I would assume she is a girl who is his friend. But it isn't made to teach English from Esperanto, and in the English the status of this girl is not clear. There is a romantic interest implied from the guy.

Regardless though, the word amikino (as well as amiko) should be translated as "friend" as we do not normally specify the gender of our friends in English since we commonly use a gender to describe romantic relationship with the person.

**Comment by georgjaehnig** [comment]
> Regardless though, the word amikino (as well as amiko) should be translated as "friend"

OK, well, then do so. I do not object.

**Comment by georgjaehnig** [comment]
Fixed in 89da7337570de97c1c3e2ea6c62e2a358b881dd1.
