### ISSUE TITLE
[Plibonigo] Aldoni ikonojn al la lingvomenuo

### ISSUE THREAD

**Issue by benahm** [Esperanto/kurso-zagreba-metodo#98]
Vi povas uzi tiun
https://github.com/usrz/bootstrap-languages

**Comment by georgjaehnig** [comment]
Saluton! Dankon pri via sugesto. Nu, laŭ mi tio ne estas gravaĵo, kaj ankaŭ ne multe plibonigos la aspekton.

Mi mem ne volas doni tempon al tio, sed se iun alian volas, bone.

(Sed ankaŭ bonus resti sendepende de aliaj bibliotekoj.)
