### ISSUE TITLE
Lasta paĝo

### ISSUE THREAD

**Issue by georgjaehnig** [Esperanto/kurso-zagreba-metodo#99]
Aldonu lasta paĝon kun
- informoj pri Esperanto enrete
- skatolo por registri al dissendlisto
- ...

**Comment by GrizaLeono** [comment]
Jen iom enigma peto, kara Georg. Kie estas tiu lasta paĝo, kiun mi devas aldoni?

**Comment by georgjaehnig** [comment]
Saluton, tio ne temas pri vi. Vi nur ricevas ĉiujn mesaĝon de la
Github-sistemo. Bonvole ignori ilin. :)

2016-05-27 16:59 GMT+02:00 GrizaLeono <notifications@github.com>:

> Jen iom enigma peto, kara Georg. Kie estas tiu lasta paĝo, kiun mi devas
> aldoni?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Esperanto/kurso-zagreba-metodo/issues/99#issuecomment-222169248>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCsFLr-NC0tlfX5iY88ZC5yFcx8VnC7ks5qFwbQgaJpZM4IoYPB>
> .
>



-- 
Georg | http://www.findfind.it - search with shortcuts

**Comment by GrizaLeono** [comment]
Ha, bone! Dankon.

**Comment by georgjaehnig** [comment]
Farite. Simple redaktu `enhavo/tradukenda/[lingvo]/post.md`.

Se ĝi ne malplenas, aperas ligilon sur la hejmpaĝo, kiel sur https://learn.esperanto.com/hr/
